#!/bin/sh

#DBs="surfer-double.db surfer-core.db  surfer-core-interior.db  cgal-ss-interior.db "
DBs="monos-cgal/monos.db monos-cgal/monos-oldcgal.db "
./plot-surfer.R --compare-plot-4 out/plot-compare-runtime.pdf `echo $DBs`
./plot-surfer.R --compare-plot-4 --memory out/plot-compare-memory.pdf  `echo $DBs`

#./plot-surfer.R --pdfsize=2 --compare-plot-2 --color-dirs out/plot-compare-input-types-surfer.pdf ./surfer-core-interior.db
#./plot-surfer.R --pdfsize=2 --compare-plot-2 --color-dirs out/plot-compare-input-types-cgal.pdf ./cgal-ss-interior.db

./plot-surfer.R --pdfsize=2 --compare-plot-4 out/plot-compare-monos-monosoldcgal.pdf monos-cgal/monos.db monos-cgal/monos-oldcgal.db
